package com.exercise.demo.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.*;

@Entity
public class Address {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //The ID is auto-generated by the database.
    private Long id;

    @Column(name = "street_name")
    private String streetName;

    @Column(name = "street_number")
    private String streetNumber;

    @Column(name = "zip_code")
    private String zipCode;

    private String city;

    //relationship with country fk
    //An Address belongs to one Country
    //A Country can have many Addresses
    @ManyToOne
    @JoinColumn(name = "country_code", referencedColumnName = "name")
    private Country country;

    //constructor

    public Address (){}
    public Address(String streetName, String streetNumber, String zipCode, String city, Country country){
        this.streetName = streetName;
        this.streetNumber = streetNumber;
        this.zipCode = zipCode;
        this.city = city;
        this.country = country;
    }


    //getters setters

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }



    public String getStreetName() { return streetName; }
    public void setStreetName(String streetName) { this.streetName = streetName; }



    public String getStreetNumber() { return streetNumber; }
    public void setStreetNumber(String streetNumber) { this.streetNumber = streetNumber; }



    public String getZipCode() { return zipCode; }
    public void setZipCode(String zipCode) { this.zipCode = zipCode; }

    public String getCity() { return city; }
    public void setCity(String city) { this.city = city; }

    public Country getCountry() { return country; }
    public void setCountry(Country country) { this.country = country; }
}
